server:
  port: 8080
spring:
  application:
    #应用名称，默认项目名
    name: reggie_take_out
  #mysql配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: "020316"
  #邮箱配置
  mail:
    #自己的邮箱
    username: 1977216208@qq.com
    #平台地址，这里用的是qq邮箱，使用其他邮箱请更换
    host: smtp.qq.com
    #授权码
    password: cqzfhpagyvuqjfjb
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  #redis配置
  redis:
    host: localhost
    port: 6379
    database: 0

  cache:
    redis:
      time-to-live: 1800000 #设置缓存数据过期时间

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID


#配置mapper
mybatis:
  mapper-locations: classpath:mapper/*.xml


reggie:
  picture:
    path: D:\reggiePicture\